# Generated by Django 2.1.7 on 2019-03-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='full_description',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='short_description',
            field=models.CharField(max_length=50),
        ),
    ]
