# Generated by Django 2.1.7 on 2019-03-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_auto_20190304_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
