# Generated by Django 2.1.7 on 2019-03-16 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_achievement_home_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='creator_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='creator_photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
