# Generated by Django 2.1.7 on 2019-03-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('linkedin', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
