# Generated by Django 2.1.7 on 2019-03-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190303_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook',
            new_name='twitter',
        ),
    ]
