# Generated by Django 2.1.7 on 2019-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190320_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
