# Generated by Django 2.1.7 on 2019-03-06 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_form_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
