# Generated by Django 2.1.7 on 2019-03-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_listing', '0002_event_google_form_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_6',
        ),
    ]
