# Generated by Django 2.1.7 on 2019-03-07 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_listing', '0003_auto_20190306_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_map_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='google_form_link',
            field=models.CharField(max_length=500),
        ),
    ]
