# Generated by Django 2.1.7 on 2019-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_listing', '0004_auto_20190307_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_2',
            field=models.TextField(blank=True),
        ),
    ]
