# Generated by Django 2.1.7 on 2019-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_listing', '0005_event_description_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_3',
            field=models.TextField(blank=True),
        ),
    ]
