# Generated by Django 2.1.7 on 2019-04-03 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('internship_profile', models.CharField(max_length=200)),
                ('internship_duration', models.CharField(max_length=200)),
                ('internship_details', models.CharField(max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
