# Generated by Django 2.1.7 on 2019-03-03 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
