# Generated by Django 2.1.7 on 2019-03-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190314_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create_photo',
            new_name='creator_photo',
        ),
    ]
