# Generated by Django 2.1.7 on 2019-03-12 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='name',
            new_name='college_company_name',
        ),
        migrations.RenameField(
            model_name='registrationform',
            old_name='text',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='date_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='github_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='internship_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='resume',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='roll_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
