# Generated by Django 2.1.7 on 2019-03-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190312_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='photo',
        ),
    ]
