# Generated by Django 2.1.7 on 2019-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_registrationform_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
