# Generated by Django 2.1.7 on 2019-03-09 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('past_event_listing', '0002_auto_20190306_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_event',
            name='google_map_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
