# Generated by Django 2.1.7 on 2019-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_event_listing', '0003_past_event_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_event',
            name='description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='past_event',
            name='description_3',
            field=models.TextField(blank=True),
        ),
    ]
